---
- hosts: all
  become: true
  pre_tasks:

  - name: dnf and epel installation
    yum:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Install updates (CentOS)
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "CentOS"

- hosts: centos
  become: true
  roles:
    - centos
